### PR TITLE
Merge from zhuoc-dev branch

### PR DESCRIPTION
**Pull request by chenzhuo914**

### CODE REVIEW

**Comment by gustavo-moreira** [comment]
Could you split this commit into two?
One for the issue #190 and a second one for the #191?

There are some additional checks that I want to do in the latter before approving it.

**Comment by chenzhuo914** [comment]
@gustavo-moreira 
The commits are actually separate for different fixes. Please click the "Commits" tab and you can review each individual commit.

And thanks for pointing out the upload feature. It seems that the report downloaded from AWFE will always have header and summary, I will add a patch to handle it properly (basically falls back to old behavior for that case).

**Comment by chenzhuo914** [comment]
@gustavo-moreira Fix for "offline import" is committed in 216dd01922d04db46e477aa1ca59d9623b03e698.

**Comment by gustavo-moreira** [comment]
LGTM!

It would be great to have a second pair of eyes review this before merging.

**Comment by chenzhuo914** [comment]
@joeltoby Joel could you also take a look at this pull request? Thanks a lot~

**Pull request merged**
